### PR TITLE
Error on unknown command line options

### PR DESCRIPTION
**Pull request by sevagh**

### CODE REVIEW

**Comment by sevagh** [comment]
Any updates on this?

**Comment by brson** [comment]
Sorry this was missed for so long. Feel free to ping me directly if it happens again.

**Comment by sevagh** [comment]
The let is probably a bashism. I looked it up and its not POSIX compliant.

**Comment by sevagh** [comment]
If I rewrite it with POSIX-compliant syntax is the idea still good? Wasn't sure how to deal with the kinda 2 disjoint blocks of command line argument parsing without this counter increment strategy.

**Comment by brson** [comment]
Yes, the idea is good, if it's done in pure sh.

**Pull request closed without merging**
