### PR TITLE
Check for root *before* downloading

### PR DESCRIPTION
**Pull request by mark-i-m**
Resolves rust-lang/rust#24052

Check for root after checking that `id` command exists

Update travis config to use sudo

### CODE REVIEW

**Comment by mark-i-m** [comment]
@GuillaumeGomez No longer failing travis ;)

**Comment by GuillaumeGomez** [comment]
Great, thanks!

cc @alexcrichton

**Comment by brson** [comment]
Thanks!

**Comment by mark-i-m** [comment]
:smile:

**Comment by therustmonk** [comment]
I even can't see the `--help` with MinGW. It needs `root` permissions (which I can't take).

**Pull request merged**
