### PR TITLE
V2 manifests

### PR DESCRIPTION
**Pull request by brson**
This teaches rustup.sh to read [V2 manifests](https://github.com/rust-lang/rust-buildbot/pull/44), adds the `--with-target` flag, which is used during the initial install to pull down additional standard libraries, the `--add-target` flag, which adds a target to an existing installation, and the `--list-available-targets` flag, which lists the targets available to an already-installed rust.

This has only been unit tested on Linux, Windows and Mac, not tested live, so don't merge yet.

I'll be happy to squash if this history is too ugly.

r? @alexcrichton cc @edunham

### CODE REVIEW

**Comment by brson** [comment]
Untabifying made the diff big. Here's one that starts from after untabifying: https://github.com/rust-lang/rustup/compare/3c96043...next

**Comment by alexcrichton** [comment]
I think that `<<<` allows specifying a variable as stdin to a command so the routines that are creating a temporary file, reading it in, and then removing it may be able to use that instead? Not entirely sure if that works out with while loops though.

**Comment by alexcrichton** [comment]
r=me, although as usual wasn't necessarily heavily scrutinized, I trust this plus the level of tests though, so I'm pretty confident it'll work out!

**Comment by KennethAdamMiller** [comment]
Supposing you clone and then checkout branch next, and then try to use muslrust for a static build for a run-anywhere capability with:

./rustup.sh --with-target musl --prefix=./muslrust 
rustc --target=x86_64-unknown-linux-musl test.rs

you get: error: can't find crate for `std`

How do I compile a hello world with musl rust if these steps don't work?

**Pull request merged**
